# Generated by Django 3.1 on 2020-08-16 04:12

import apps.base.models.product
import apps.base.models.usercustom
import apps.base.rename_image
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellidos')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero Móvil')),
                ('avatar', models.ImageField(blank=True, default='avatar/default_avatar.png', max_length=255, null=True, storage=apps.base.rename_image.RenameImage(), upload_to=apps.base.models.usercustom.image_path)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PyDistrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ANCON', 'ANCON'), ('ATE', 'ATE'), ('BARRANCO', 'BARRANCO'), ('BREÑA', 'BREÑA'), ('CARABAYLLO', 'CARABAYLLO'), ('CHACLACAYO', 'CHACLACAYO'), ('CHORRILLOS', 'CHORRILLOS'), ('CIENEGUILLA', 'CIENEGUILLA'), ('COMAS', 'COMAS'), ('EL AGUSTINO', 'EL AGUSTINO'), ('INDEPENDENCIA', 'INDEPENDENCIA'), ('JESUS MARIA', 'JESUS MARIA'), ('LA MOLINA', 'LA MOLINA'), ('LA VICTORIA', 'LA VICTORIA'), ('LIMA', 'LIMA'), ('LINCE', 'LINCE'), ('LOS OLIVOS', 'LOS OLIVOS'), ('LURIGANCHO', 'LURIGANCHO'), ('LURIN', 'LURIN'), ('MAGDALENA DEL MAR', 'MAGDALENA DEL MAR'), ('MIRAFLORES', 'MIRAFLORES'), ('PACHACAMAC', 'PACHACAMAC'), ('MIRAFLORES', 'MIRAFLORES'), ('PUCUSANA', 'PUCUSANA'), ('PUEBLO LIBRE', 'PUEBLO LIBRE'), ('PUENTE PIEDRA', 'PUENTE PIEDRA'), ('PUNTA HERMOSA', 'PUNTA HERMOSA'), ('PUNTA NEGRA', 'PUNTA NEGRA'), ('RIMAC', 'RIMAC'), ('SAN BARTOLO', 'SAN BARTOLO'), ('SAN BORJA', 'SAN BORJA'), ('SAN ISIDRO', 'SAN ISIDRO'), ('SAN JUAN DE LURIGANCHO', 'SAN JUAN DE LURIGANCHO'), ('SAN JUAN DE MIRAFLORES', 'SAN JUAN DE MIRAFLORES'), ('SAN LUIS', 'SAN LUIS'), ('SAN MARTIN DE PORRES', 'SAN MARTIN DE PORRES'), ('SAN MIGUEL', 'SAN MIGUEL'), ('SANTA ANITA', 'SANTA ANITA'), ('SANTA ROSA', 'SANTA ROSA'), ('SANTIAGO DE SURCO', 'SANTIAGO DE SURCO'), ('SURQUILLO', 'SURQUILLO'), ('VILLA EL SALVADOR', 'VILLA EL SALVADOR'), ('VILLA MARIA DEL TRIUNFO', 'VILLA MARIA DEL TRIUNFO')], default='LIMA', max_length=64, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='PyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo/Precio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('youtube_video', models.CharField(blank=True, max_length=300, null=True)),
                ('img', models.ImageField(blank=True, default='product/default_product.png', max_length=255, null=True, storage=apps.base.rename_image.RenameImage(), upload_to=apps.base.models.product.image_path)),
                ('type', models.CharField(choices=[('product', 'Almacenable'), ('consu', 'Consumible'), ('service', 'Servicio'), ('software', 'Software')], default='consu', max_length=64, verbose_name='Tipo')),
                ('dueño', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PyOficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
            },
        ),
        migrations.AddField(
            model_name='pyuser',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.pydistrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='pyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='pyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
